### ISSUE TITLE
what is the url for calling an endpoint using requests from within a test?

### ISSUE THREAD

**Issue by Martlark** [TotallyNotChase/flask-unittest#5]
Example:

```Python
    def test_url_post(self, app, client):
        print(app.config)
        url = f"http://127.0.0.1:{app.config['PORT']}/test_post/"
```

**Comment by TotallyNotChase** [comment]
You can do that using `client`, which is of type `FlaskClient`. Check the relevant documentation for that on the [flask docs](https://flask.palletsprojects.com/en/1.1.x/api/#flask.testing.FlaskClient).

There's also some examples in the README and in the `tests/` directory.
