### ISSUE TITLE
Update release tags to install via pip

### ISSUE THREAD

**Issue by jonibim** [TotallyNotChase/flask-unittest#6]
Would it be possible to update the release tags such that installing `flask-unittest` with the latest fix https://github.com/TotallyNotChase/flask-unittest/pull/4 could be done through `pip`. Currently the release tags 0.1.2 does not include this fix

**Comment by TotallyNotChase** [comment]
whoops, I had forgotten to do this. I uploaded v0.1.3, let me know if it works for you.

**Comment by jonibim** [comment]
Amazing! It works now. Thank you!  :)
